/**
 * Mock data simulando respuestas de base de datos.
 * Clasificación individual — VI Campeonato Nacional Salmónidos Lance Mosca
 *
 * Estructura de mangas (8 en total):
 *   Día 1 Mañana  → Manga 1 (Turno A pesca) | Manga 2 (Turno B pesca)  [paralelas]
 *   Día 1 Tarde   → Manga 3 (Turno A pesca) | Manga 4 (Turno B pesca)  [paralelas]
 *   Día 2 Mañana  → Manga 5 (Turno B pesca) | Manga 6 (Turno A pesca)  [paralelas, invertido]
 *   Día 2 Tarde   → Manga 7 (Turno B pesca) | Manga 8 (Turno A pesca)  [paralelas, invertido]
 *
 *   Turno A pesca en: 1, 3, 6, 8
 *   Turno B pesca en: 2, 4, 5, 7
 */

import type {
  Participante,
  PescadorStats,
  RecentCatch,
  BestFish,
  MangaStats,
} from "@/types";
import { MANGAS } from "./competition";


// ─── Participantes ─────────────────────────────────────────────────────────────
// Turno A: plicas pares · Turno B: plicas impares

export const MOCK_PARTICIPANTES: Participante[] = [
  {
    id: "p-001",
    nombre: "Carlos Rodríguez Vega",
    plica: "01",
    club: "SD Pesca León",
    turno: "B",
    tramo: "Tramo 1 - Boñar",
    rio: "Río Porma",
    createdAt: new Date("2025-03-01"),
    updatedAt: new Date("2025-03-01"),
  },
  {
    id: "p-002",
    nombre: "Javier Fernández Lago",
    plica: "02",
    club: "Club Mosca Galicia",
    turno: "A",
    tramo: "Tramo 2 - Valdeón",
    rio: "Río Cares",
    createdAt: new Date("2025-03-01"),
    updatedAt: new Date("2025-03-01"),
  },
  {
    id: "p-003",
    nombre: "Marcos García Prieto",
    plica: "03",
    club: "AM Pesca Madrid",
    turno: "B",
    tramo: "Tramo 1 - Boñar",
    rio: "Río Porma",
    createdAt: new Date("2025-03-01"),
    updatedAt: new Date("2025-03-01"),
  },
  {
    id: "p-004",
    nombre: "Luis Álvarez Suárez",
    plica: "04",
    club: "Club Salmonídeos Asturias",
    turno: "A",
    tramo: "Tramo 3 - Riaño",
    rio: "Río Esla",
    createdAt: new Date("2025-03-01"),
    updatedAt: new Date("2025-03-01"),
  },
  {
    id: "p-005",
    nombre: "Pablo Martínez Torres",
    plica: "05",
    club: "SD Pesca León",
    turno: "B",
    tramo: "Tramo A - Ponferrada",
    rio: "Río Sil",
    createdAt: new Date("2025-03-01"),
    updatedAt: new Date("2025-03-01"),
  },
  {
    id: "p-006",
    nombre: "Antonio Iglesias Ramos",
    plica: "06",
    club: "Club Mosca Cantabria",
    turno: "A",
    tramo: "Tramo 2 - Valdeón",
    rio: "Río Cares",
    createdAt: new Date("2025-03-01"),
    updatedAt: new Date("2025-03-01"),
  },
  {
    id: "p-007",
    nombre: "David Blanco Herrero",
    plica: "07",
    club: "Federación Pesca CyL",
    turno: "B",
    tramo: "Tramo B - Quiroga",
    rio: "Río Sil",
    createdAt: new Date("2025-03-02"),
    updatedAt: new Date("2025-03-02"),
  },
  {
    id: "p-008",
    nombre: "Sergio Castillo Mora",
    plica: "08",
    club: "Club Mosca Galicia",
    turno: "A",
    tramo: "Tramo 1 - Puebla de Sanabria",
    rio: "Río Tera",
    createdAt: new Date("2025-03-02"),
    updatedAt: new Date("2025-03-02"),
  },
  {
    id: "p-009",
    nombre: "Roberto Fuentes Díaz",
    plica: "09",
    club: "AM Pesca Madrid",
    turno: "B",
    tramo: "Tramo 3 - Riaño",
    rio: "Río Esla",
    createdAt: new Date("2025-03-02"),
    updatedAt: new Date("2025-03-02"),
  },
  {
    id: "p-010",
    nombre: "Fernando Ortega Nieto",
    plica: "10",
    club: "Club Salmonídeos Asturias",
    turno: "A",
    tramo: "Tramo 2 - Puebla de Sanabria",
    rio: "Río Tera",
    createdAt: new Date("2025-03-02"),
    updatedAt: new Date("2025-03-02"),
  },
  {
    id: "p-011",
    nombre: "Andrés López Sánchez",
    plica: "11",
    club: "SD Pesca León",
    turno: "B",
    tramo: "Tramo 1 - Boñar",
    rio: "Río Porma",
    createdAt: new Date("2025-03-03"),
    updatedAt: new Date("2025-03-03"),
  },
  {
    id: "p-012",
    nombre: "Miguel Pérez Castro",
    plica: "12",
    club: "Club Mosca Cantabria",
    turno: "A",
    tramo: "Tramo A - Ponferrada",
    rio: "Río Sil",
    createdAt: new Date("2025-03-03"),
    updatedAt: new Date("2025-03-03"),
  },
  {
    id: "p-013",
    nombre: "Raúl González Expósito",
    plica: "13",
    club: "Federación Pesca CyL",
    turno: "B",
    tramo: "Tramo 2 - Valdeón",
    rio: "Río Cares",
    createdAt: new Date("2025-03-03"),
    updatedAt: new Date("2025-03-03"),
  },
  {
    id: "p-014",
    nombre: "Iván Moreno Bravo",
    plica: "14",
    club: "AM Pesca Madrid",
    turno: "A",
    tramo: "Tramo 3 - Riaño",
    rio: "Río Esla",
    createdAt: new Date("2025-03-03"),
    updatedAt: new Date("2025-03-03"),
  },
  {
    id: "p-015",
    nombre: "Óscar Jiménez Navarro",
    plica: "15",
    club: "Club Mosca Galicia",
    turno: "B",
    tramo: "Tramo B - Quiroga",
    rio: "Río Sil",
    createdAt: new Date("2025-03-04"),
    updatedAt: new Date("2025-03-04"),
  },
  {
    id: "p-016",
    nombre: "Tomás Serrano Gil",
    plica: "16",
    club: "SD Pesca León",
    turno: "A",
    tramo: "Tramo 1 - Puebla de Sanabria",
    rio: "Río Tera",
    createdAt: new Date("2025-03-04"),
    updatedAt: new Date("2025-03-04"),
  },
  {
    id: "p-017",
    nombre: "Eduardo Rubio Vargas",
    plica: "17",
    club: "Club Salmonídeos Asturias",
    turno: "B",
    tramo: "Tramo 1 - Boñar",
    rio: "Río Porma",
    createdAt: new Date("2025-03-04"),
    updatedAt: new Date("2025-03-04"),
  },
  {
    id: "p-018",
    nombre: "Vicente Molina Cano",
    plica: "18",
    club: "Club Mosca Cantabria",
    turno: "A",
    tramo: "Tramo 3 - Riaño",
    rio: "Río Esla",
    createdAt: new Date("2025-03-04"),
    updatedAt: new Date("2025-03-04"),
  },
  {
    id: "p-019",
    nombre: "Adrián Cruz Mendoza",
    plica: "19",
    club: "Federación Pesca CyL",
    turno: "B",
    tramo: "Tramo A - Ponferrada",
    rio: "Río Sil",
    createdAt: new Date("2025-03-05"),
    updatedAt: new Date("2025-03-05"),
  },
  {
    id: "p-020",
    nombre: "Manuel Romero Peña",
    plica: "20",
    club: "AM Pesca Madrid",
    turno: "A",
    tramo: "Tramo 2 - Puebla de Sanabria",
    rio: "Río Tera",
    createdAt: new Date("2025-03-05"),
    updatedAt: new Date("2025-03-05"),
  },
  {
    id: "p-021",
    nombre: "Héctor Reyes Campos",
    plica: "21",
    club: "Club Mosca Galicia",
    turno: "B",
    tramo: "Tramo 2 - Valdeón",
    rio: "Río Cares",
    createdAt: new Date("2025-03-05"),
    updatedAt: new Date("2025-03-05"),
  },
  {
    id: "p-022",
    nombre: "Nicolás Delgado Vidal",
    plica: "22",
    club: "SD Pesca León",
    turno: "A",
    tramo: "Tramo 3 - Riaño",
    rio: "Río Esla",
    createdAt: new Date("2025-03-05"),
    updatedAt: new Date("2025-03-05"),
  },
  {
    id: "p-023",
    nombre: "Gonzalo Muñoz Tejeda",
    plica: "23",
    club: "Club Salmonídeos Asturias",
    turno: "B",
    tramo: "Tramo B - Quiroga",
    rio: "Río Sil",
    createdAt: new Date("2025-03-06"),
    updatedAt: new Date("2025-03-06"),
  },
  {
    id: "p-024",
    nombre: "Felipe Aguilar Soler",
    plica: "24",
    club: "Club Mosca Cantabria",
    turno: "A",
    tramo: "Tramo 1 - Puebla de Sanabria",
    rio: "Río Tera",
    createdAt: new Date("2025-03-06"),
    updatedAt: new Date("2025-03-06"),
  },
];

// ─── Clasificación individual ──────────────────────────────────────────────────
// Cada pescador tiene capturas repartidas en sus 4 mangas (según turno A o B)
// Turno A → mangas 1, 3, 6, 8  |  Turno B → mangas 2, 4, 5, 7
// mangaResultados: { tallasEnCm (ordenadas desc), puntos, posicion dentro de la manga }

export const MOCK_CLASIFICACION: PescadorStats[] = [
  {
    pescadorId: "p-004",  // Turno A → mangas 1,3,6,8
    nombre: "Luis Álvarez Suárez",
    plica: "04",
    club: "Club Salmonídeos Asturias",
    turno: "A",
    tramo: "Tramo 3 - Riaño",
    rio: "Río Esla",
    totalCapturas: 9,
    capturasValidas: 8,
    capturasMenores19: 1,
    totalCm: 218,
    totalPuntos: 5_520,
    mejorPieza: 34,
    posicion: 1,
    mangaResultados: {
      1: { tallasEnCm: [34, 32, 31], puntos: 2_050, posicion: 1 },
      3: { tallasEnCm: [30, 28],     puntos: 1_450, posicion: 2 },
      6: { tallasEnCm: [29, 26],     puntos: 1_370, posicion: 1 },
      8: { tallasEnCm: [28, 27],     puntos: 1_300, posicion: 2 },
    },
  },
  {
    pescadorId: "p-002",  // Turno A → mangas 1,3,6,8
    nombre: "Javier Fernández Lago",
    plica: "02",
    club: "Club Mosca Galicia",
    turno: "A",
    tramo: "Tramo 2 - Valdeón",
    rio: "Río Cares",
    totalCapturas: 8,
    capturasValidas: 8,
    capturasMenores19: 0,
    totalCm: 204,
    totalPuntos: 5_180,
    mejorPieza: 33,
    posicion: 2,
    mangaResultados: {
      1: { tallasEnCm: [33, 32],     puntos: 1_590, posicion: 2 },
      3: { tallasEnCm: [31, 30],     puntos: 1_480, posicion: 1 },
      6: { tallasEnCm: [27, 26],     puntos: 1_290, posicion: 2 },
      8: { tallasEnCm: [31, 25],     puntos: 1_340, posicion: 1 },
    },
  },
  {
    pescadorId: "p-001",  // Turno B → mangas 2,4,5,7
    nombre: "Carlos Rodríguez Vega",
    plica: "01",
    club: "SD Pesca León",
    turno: "B",
    tramo: "Tramo 1 - Boñar",
    rio: "Río Porma",
    totalCapturas: 8,
    capturasValidas: 7,
    capturasMenores19: 1,
    totalCm: 192,
    totalPuntos: 4_940,
    mejorPieza: 31,
    posicion: 3,
    mangaResultados: {
      2: { tallasEnCm: [31, 29],     puntos: 1_500, posicion: 1 },
      4: { tallasEnCm: [28, 26],     puntos: 1_320, posicion: 1 },
      5: { tallasEnCm: [27, 25],     puntos: 1_250, posicion: 1 },
      7: { tallasEnCm: [26, 24],     puntos: 1_200, posicion: 1 },
    },
  },
  {
    pescadorId: "p-005",  // Turno B → mangas 2,4,5,7
    nombre: "Pablo Martínez Torres",
    plica: "05",
    club: "SD Pesca León",
    turno: "B",
    tramo: "Tramo A - Ponferrada",
    rio: "Río Sil",
    totalCapturas: 7,
    capturasValidas: 7,
    capturasMenores19: 0,
    totalCm: 181,
    totalPuntos: 4_720,
    mejorPieza: 30,
    posicion: 4,
    mangaResultados: {
      2: { tallasEnCm: [30, 29],     puntos: 1_450, posicion: 2 },
      4: { tallasEnCm: [28, 27],     puntos: 1_340, posicion: 2 },
      5: { tallasEnCm: [26, 25],     puntos: 1_240, posicion: 2 },
      7: { tallasEnCm: [24],         puntos:   580, posicion: 3 },
    },
  },
  {
    pescadorId: "p-008",  // Turno A → mangas 1,3,6,8
    nombre: "Sergio Castillo Mora",
    plica: "08",
    club: "Club Mosca Galicia",
    turno: "A",
    tramo: "Tramo 1 - Puebla de Sanabria",
    rio: "Río Tera",
    totalCapturas: 7,
    capturasValidas: 6,
    capturasMenores19: 1,
    totalCm: 168,
    totalPuntos: 4_460,
    mejorPieza: 29,
    posicion: 5,
    mangaResultados: {
      1: { tallasEnCm: [29, 28],     puntos: 1_400, posicion: 3 },
      3: { tallasEnCm: [27, 26],     puntos: 1_290, posicion: 3 },
      6: { tallasEnCm: [25, 24],     puntos: 1_190, posicion: 3 },
      8: { tallasEnCm: [23],         puntos:   560, posicion: 3 },
    },
  },
  {
    pescadorId: "p-009",  // Turno B → mangas 2,4,5,7
    nombre: "Roberto Fuentes Díaz",
    plica: "09",
    club: "AM Pesca Madrid",
    turno: "B",
    tramo: "Tramo 3 - Riaño",
    rio: "Río Esla",
    totalCapturas: 6,
    capturasValidas: 6,
    capturasMenores19: 0,
    totalCm: 158,
    totalPuntos: 4_260,
    mejorPieza: 28,
    posicion: 6,
    mangaResultados: {
      2: { tallasEnCm: [28, 27],     puntos: 1_680, posicion: 3 },
      4: { tallasEnCm: [26, 25],     puntos: 1_560, posicion: 3 },
      5: { tallasEnCm: [23],         puntos:   540, posicion: 4 },
      7: { tallasEnCm: [22],         puntos:   520, posicion: 4 },
    },
  },
  {
    pescadorId: "p-015",  // Turno B → mangas 2,4,5,7
    nombre: "Óscar Jiménez Navarro",
    plica: "15",
    club: "Club Mosca Galicia",
    turno: "B",
    tramo: "Tramo B - Quiroga",
    rio: "Río Sil",
    totalCapturas: 6,
    capturasValidas: 5,
    capturasMenores19: 1,
    totalCm: 145,
    totalPuntos: 3_980,
    mejorPieza: 27,
    posicion: 7,
    mangaResultados: {
      2: { tallasEnCm: [27, 26],     puntos: 1_610, posicion: 4 },
      4: { tallasEnCm: [25],         puntos:   750, posicion: 5 },
      5: { tallasEnCm: [24, 23],     puntos: 1_420, posicion: 3 },
      7: { tallasEnCm: [22],         puntos:   520, posicion: 5 },
    },
  },
  {
    pescadorId: "p-003",  // Turno B → mangas 2,4,5,7
    nombre: "Marcos García Prieto",
    plica: "03",
    club: "AM Pesca Madrid",
    turno: "B",
    tramo: "Tramo 1 - Boñar",
    rio: "Río Porma",
    totalCapturas: 6,
    capturasValidas: 5,
    capturasMenores19: 1,
    totalCm: 138,
    totalPuntos: 3_780,
    mejorPieza: 26,
    posicion: 8,
    mangaResultados: {
      2: { tallasEnCm: [26, 25],     puntos: 1_540, posicion: 5 },
      4: { tallasEnCm: [24, 23],     puntos: 1_420, posicion: 4 },
      5: { tallasEnCm: [21],         puntos:   500, posicion: 5 },
      7: { tallasEnCm: [20],         puntos:   480, posicion: 6 },
    },
  },
  {
    pescadorId: "p-013",  // Turno B → mangas 2,4,5,7
    nombre: "Raúl González Expósito",
    plica: "13",
    club: "Federación Pesca CyL",
    turno: "B",
    tramo: "Tramo 2 - Valdeón",
    rio: "Río Cares",
    totalCapturas: 5,
    capturasValidas: 5,
    capturasMenores19: 0,
    totalCm: 128,
    totalPuntos: 3_560,
    mejorPieza: 26,
    posicion: 9,
    mangaResultados: {
      2: { tallasEnCm: [26, 25],     puntos: 1_540, posicion: 5 },
      4: { tallasEnCm: [24],         puntos:   730, posicion: 6 },
      5: { tallasEnCm: [23],         puntos:   680, posicion: 6 },
      7: { tallasEnCm: [22],         puntos:   650, posicion: 7 },
    },
  },
  {
    pescadorId: "p-006",  // Turno A → mangas 1,3,6,8
    nombre: "Antonio Iglesias Ramos",
    plica: "06",
    club: "Club Mosca Cantabria",
    turno: "A",
    tramo: "Tramo 2 - Valdeón",
    rio: "Río Cares",
    totalCapturas: 5,
    capturasValidas: 5,
    capturasMenores19: 0,
    totalCm: 122,
    totalPuntos: 3_440,
    mejorPieza: 25,
    posicion: 10,
    mangaResultados: {
      1: { tallasEnCm: [25, 24],     puntos: 1_465, posicion: 4 },
      3: { tallasEnCm: [23],         puntos:   680, posicion: 6 },
      6: { tallasEnCm: [22],         puntos:   655, posicion: 7 },
      8: { tallasEnCm: [21],         puntos:   630, posicion: 5 },
    },
  },
  {
    pescadorId: "p-007",  // Turno B → mangas 2,4,5,7
    nombre: "David Blanco Herrero",
    plica: "07",
    club: "Federación Pesca CyL",
    turno: "B",
    tramo: "Tramo B - Quiroga",
    rio: "Río Sil",
    totalCapturas: 5,
    capturasValidas: 4,
    capturasMenores19: 1,
    totalCm: 108,
    totalPuntos: 3_100,
    mejorPieza: 24,
    posicion: 11,
    mangaResultados: {
      2: { tallasEnCm: [23, 22],     puntos: 1_370, posicion: 7 },
      4: { tallasEnCm: [21],         puntos:   620, posicion: 7 },
      5: { tallasEnCm: [20],         puntos:   590, posicion: 7 },
      7: { tallasEnCm: [19],         puntos:   560, posicion: 8 },
    },
  },
  {
    pescadorId: "p-011",  // Turno B → mangas 2,4,5,7
    nombre: "Andrés López Sánchez",
    plica: "11",
    club: "SD Pesca León",
    turno: "B",
    tramo: "Tramo 1 - Boñar",
    rio: "Río Porma",
    totalCapturas: 4,
    capturasValidas: 4,
    capturasMenores19: 0,
    totalCm: 98,
    totalPuntos: 2_960,
    mejorPieza: 25,
    posicion: 12,
    mangaResultados: {
      2: { tallasEnCm: [25],         puntos:   750, posicion: 6 },
      4: { tallasEnCm: [24],         puntos:   730, posicion: 8 },
      5: { tallasEnCm: [24],         puntos:   730, posicion: 8 },
      7: { tallasEnCm: [25],         puntos:   750, posicion: 5 },
    },
  },
  {
    pescadorId: "p-014",  // Turno A → mangas 1,3,6,8
    nombre: "Iván Moreno Bravo",
    plica: "14",
    club: "AM Pesca Madrid",
    turno: "A",
    tramo: "Tramo 3 - Riaño",
    rio: "Río Esla",
    totalCapturas: 4,
    capturasValidas: 4,
    capturasMenores19: 0,
    totalCm: 94,
    totalPuntos: 2_880,
    mejorPieza: 24,
    posicion: 13,
    mangaResultados: {
      1: { tallasEnCm: [24],         puntos:   735, posicion: 7 },
      3: { tallasEnCm: [24],         puntos:   735, posicion: 5 },
      6: { tallasEnCm: [23],         puntos:   705, posicion: 5 },
      8: { tallasEnCm: [23],         puntos:   705, posicion: 4 },
    },
  },
  {
    pescadorId: "p-019",  // Turno B → mangas 2,4,5,7
    nombre: "Adrián Cruz Mendoza",
    plica: "19",
    club: "Federación Pesca CyL",
    turno: "B",
    tramo: "Tramo A - Ponferrada",
    rio: "Río Sil",
    totalCapturas: 4,
    capturasValidas: 3,
    capturasMenores19: 1,
    totalCm: 82,
    totalPuntos: 2_540,
    mejorPieza: 21,
    posicion: 14,
    mangaResultados: {
      2: { tallasEnCm: [21],         puntos:   635, posicion: 9 },
      4: { tallasEnCm: [20],         puntos:   605, posicion: 9 },
      5: { tallasEnCm: [20],         puntos:   605, posicion: 9 },
      7: { tallasEnCm: [21],         puntos:   635, posicion: 7 },
    },
  },
  {
    pescadorId: "p-012",  // Turno A → mangas 1,3,6,8
    nombre: "Miguel Pérez Castro",
    plica: "12",
    club: "Club Mosca Cantabria",
    turno: "A",
    tramo: "Tramo A - Ponferrada",
    rio: "Río Sil",
    totalCapturas: 3,
    capturasValidas: 3,
    capturasMenores19: 0,
    totalCm: 76,
    totalPuntos: 2_380,
    mejorPieza: 26,
    posicion: 15,
    mangaResultados: {
      1: { tallasEnCm: [26],         puntos:   790, posicion: 5 },
      3: { tallasEnCm: [25],         puntos:   760, posicion: 4 },
      6: { tallasEnCm: [25],         puntos:   760, posicion: 4 },
      8: { tallasEnCm: [],           puntos:     0, posicion: 8 },
    },
  },
  {
    pescadorId: "p-017",  // Turno B → mangas 2,4,5,7
    nombre: "Eduardo Rubio Vargas",
    plica: "17",
    club: "Club Salmonídeos Asturias",
    turno: "B",
    tramo: "Tramo 1 - Boñar",
    rio: "Río Porma",
    totalCapturas: 3,
    capturasValidas: 3,
    capturasMenores19: 0,
    totalCm: 71,
    totalPuntos: 2_220,
    mejorPieza: 24,
    posicion: 16,
    mangaResultados: {
      2: { tallasEnCm: [24],         puntos:   730, posicion: 8 },
      4: { tallasEnCm: [24],         puntos:   730, posicion: 8 },
      5: { tallasEnCm: [23],         puntos:   680, posicion: 6 },
      7: { tallasEnCm: [],           puntos:     0, posicion: 10 },
    },
  },
  {
    pescadorId: "p-022",  // Turno A → mangas 1,3,6,8
    nombre: "Nicolás Delgado Vidal",
    plica: "22",
    club: "SD Pesca León",
    turno: "A",
    tramo: "Tramo 3 - Riaño",
    rio: "Río Esla",
    totalCapturas: 3,
    capturasValidas: 2,
    capturasMenores19: 1,
    totalCm: 58,
    totalPuntos: 1_820,
    mejorPieza: 20,
    posicion: 17,
    mangaResultados: {
      1: { tallasEnCm: [20],         puntos:   610, posicion: 8 },
      3: { tallasEnCm: [19],         puntos:   580, posicion: 7 },
      6: { tallasEnCm: [19],         puntos:   580, posicion: 9 },
      8: { tallasEnCm: [],           puntos:     0, posicion: 9 },
    },
  },
  {
    pescadorId: "p-010",  // Turno A → mangas 1,3,6,8
    nombre: "Fernando Ortega Nieto",
    plica: "10",
    club: "Club Salmonídeos Asturias",
    turno: "A",
    tramo: "Tramo 2 - Puebla de Sanabria",
    rio: "Río Tera",
    totalCapturas: 2,
    capturasValidas: 2,
    capturasMenores19: 0,
    totalCm: 49,
    totalPuntos: 1_580,
    mejorPieza: 25,
    posicion: 18,
    mangaResultados: {
      1: { tallasEnCm: [25],         puntos:   760, posicion: 6 },
      3: { tallasEnCm: [],           puntos:     0, posicion: 10 },
      6: { tallasEnCm: [24],         puntos:   730, posicion: 6 },
      8: { tallasEnCm: [],           puntos:     0, posicion: 10 },
    },
  },
  {
    pescadorId: "p-021",  // Turno B → mangas 2,4,5,7
    nombre: "Héctor Reyes Campos",
    plica: "21",
    club: "Club Mosca Galicia",
    turno: "B",
    tramo: "Tramo 2 - Valdeón",
    rio: "Río Cares",
    totalCapturas: 2,
    capturasValidas: 2,
    capturasMenores19: 0,
    totalCm: 44,
    totalPuntos: 1_480,
    mejorPieza: 22,
    posicion: 19,
    mangaResultados: {
      2: { tallasEnCm: [22],         puntos:   670, posicion: 10 },
      4: { tallasEnCm: [],           puntos:     0, posicion: 11 },
      5: { tallasEnCm: [22],         puntos:   670, posicion: 10 },
      7: { tallasEnCm: [],           puntos:     0, posicion: 11 },
    },
  },
  {
    pescadorId: "p-016",  // Turno A → mangas 1,3,6,8
    nombre: "Tomás Serrano Gil",
    plica: "16",
    club: "SD Pesca León",
    turno: "A",
    tramo: "Tramo 1 - Puebla de Sanabria",
    rio: "Río Tera",
    totalCapturas: 2,
    capturasValidas: 1,
    capturasMenores19: 1,
    totalCm: 32,
    totalPuntos: 740,
    mejorPieza: 16,
    posicion: 20,
    mangaResultados: {
      1: { tallasEnCm: [16],         puntos:     0, posicion: 10 },
      3: { tallasEnCm: [],           puntos:     0, posicion: 11 },
      6: { tallasEnCm: [16],         puntos:     0, posicion: 11 },
      8: { tallasEnCm: [],           puntos:     0, posicion: 11 },
    },
  },
  {
    pescadorId: "p-018",  // Turno A → mangas 1,3,6,8
    nombre: "Vicente Molina Cano",
    plica: "18",
    club: "Club Mosca Cantabria",
    turno: "A",
    tramo: "Tramo 3 - Riaño",
    rio: "Río Esla",
    totalCapturas: 1,
    capturasValidas: 1,
    capturasMenores19: 0,
    totalCm: 21,
    totalPuntos: 520,
    mejorPieza: 21,
    posicion: 21,
    mangaResultados: {
      1: { tallasEnCm: [],           puntos:     0, posicion: 12 },
      3: { tallasEnCm: [],           puntos:     0, posicion: 12 },
      6: { tallasEnCm: [21],         puntos:   520, posicion: 8 },
      8: { tallasEnCm: [],           puntos:     0, posicion: 12 },
    },
  },
  {
    pescadorId: "p-020",  // Turno A → mangas 1,3,6,8
    nombre: "Manuel Romero Peña",
    plica: "20",
    club: "AM Pesca Madrid",
    turno: "A",
    tramo: "Tramo 2 - Puebla de Sanabria",
    rio: "Río Tera",
    totalCapturas: 1,
    capturasValidas: 1,
    capturasMenores19: 0,
    totalCm: 19,
    totalPuntos: 480,
    mejorPieza: 19,
    posicion: 22,
    mangaResultados: {
      1: { tallasEnCm: [],           puntos:     0, posicion: 12 },
      3: { tallasEnCm: [19],         puntos:   480, posicion: 8 },
      6: { tallasEnCm: [],           puntos:     0, posicion: 12 },
      8: { tallasEnCm: [],           puntos:     0, posicion: 12 },
    },
  },
  {
    pescadorId: "p-023",  // Turno B → mangas 2,4,5,7
    nombre: "Gonzalo Muñoz Tejeda",
    plica: "23",
    club: "Club Salmonídeos Asturias",
    turno: "B",
    tramo: "Tramo B - Quiroga",
    rio: "Río Sil",
    totalCapturas: 1,
    capturasValidas: 0,
    capturasMenores19: 1,
    totalCm: 15,
    totalPuntos: 0,
    mejorPieza: 15,
    posicion: 23,
    mangaResultados: {
      2: { tallasEnCm: [],           puntos:     0, posicion: 12 },
      4: { tallasEnCm: [15],         puntos:     0, posicion: 12 },
      5: { tallasEnCm: [],           puntos:     0, posicion: 12 },
      7: { tallasEnCm: [],           puntos:     0, posicion: 12 },
    },
  },
  {
    pescadorId: "p-024",  // Turno A → mangas 1,3,6,8
    nombre: "Felipe Aguilar Soler",
    plica: "24",
    club: "Club Mosca Cantabria",
    turno: "A",
    tramo: "Tramo 1 - Puebla de Sanabria",
    rio: "Río Tera",
    totalCapturas: 0,
    capturasValidas: 0,
    capturasMenores19: 0,
    totalCm: 0,
    totalPuntos: 0,
    mejorPieza: 0,
    posicion: 24,
    mangaResultados: {
      1: { tallasEnCm: [],           puntos:     0, posicion: 12 },
      3: { tallasEnCm: [],           puntos:     0, posicion: 12 },
      6: { tallasEnCm: [],           puntos:     0, posicion: 12 },
      8: { tallasEnCm: [],           puntos:     0, posicion: 12 },
    },
  },
];

// ─── Últimas capturas ──────────────────────────────────────────────────────────
// Las mangas indicadas respetan el turno del pescador

export const MOCK_RECENT_CATCHES: RecentCatch[] = [
  {
    id: "c-001",
    pescadorId: "p-004",   // Turno A → manga 8 (Día2 Tarde TurnoA) ✓
    sessionId: "s-004",
    manga: 8,
    tramo: "Tramo 3 - Riaño",
    rio: "Río Esla",
    longitudCm: 34,
    puntos: 780,
    valida: true,
    hora: "16:42",
    observaciones: "",
    juezId: null,
    createdAt: new Date("2025-04-14T16:42:00"),
    updatedAt: new Date("2025-04-14T16:42:00"),
    nombre: "Luis Álvarez Suárez",
  },
  {
    id: "c-002",
    pescadorId: "p-002",   // Turno A → manga 6 (Día2 Mañana TurnoA) ✓
    sessionId: "s-002",
    manga: 6,
    tramo: "Tramo 2 - Valdeón",
    rio: "Río Cares",
    longitudCm: 32,
    puntos: 740,
    valida: true,
    hora: "09:28",
    observaciones: "",
    juezId: null,
    createdAt: new Date("2025-04-14T09:28:00"),
    updatedAt: new Date("2025-04-14T09:28:00"),
    nombre: "Javier Fernández Lago",
  },
  {
    id: "c-003",
    pescadorId: "p-001",   // Turno B → manga 7 (Día2 Tarde TurnoB) ✓
    sessionId: "s-001",
    manga: 7,
    tramo: "Tramo 1 - Boñar",
    rio: "Río Porma",
    longitudCm: 28,
    puntos: 660,
    valida: true,
    hora: "16:15",
    observaciones: "",
    juezId: null,
    createdAt: new Date("2025-04-14T16:15:00"),
    updatedAt: new Date("2025-04-14T16:15:00"),
    nombre: "Carlos Rodríguez Vega",
  },
  {
    id: "c-004",
    pescadorId: "p-005",   // Turno B → manga 5 (Día2 Mañana TurnoB) ✓
    sessionId: "s-005",
    manga: 5,
    tramo: "Tramo A - Ponferrada",
    rio: "Río Sil",
    longitudCm: 26,
    puntos: 620,
    valida: true,
    hora: "09:54",
    observaciones: "",
    juezId: null,
    createdAt: new Date("2025-04-14T09:54:00"),
    updatedAt: new Date("2025-04-14T09:54:00"),
    nombre: "Pablo Martínez Torres",
  },
  {
    id: "c-005",
    pescadorId: "p-009",   // Turno B → manga 4 (Día1 Tarde TurnoB) ✓
    sessionId: "s-009",
    manga: 4,
    tramo: "Tramo 3 - Riaño",
    rio: "Río Esla",
    longitudCm: 16,
    puntos: 15,
    valida: false,
    hora: "15:40",
    observaciones: "Medida inferior al mínimo",
    juezId: null,
    createdAt: new Date("2025-04-13T15:40:00"),
    updatedAt: new Date("2025-04-13T15:40:00"),
    nombre: "Roberto Fuentes Díaz",
  },
  {
    id: "c-006",
    pescadorId: "p-008",   // Turno A → manga 3 (Día1 Tarde TurnoA) ✓
    sessionId: "s-008",
    manga: 3,
    tramo: "Tramo 1 - Puebla de Sanabria",
    rio: "Río Tera",
    longitudCm: 29,
    puntos: 680,
    valida: true,
    hora: "15:22",
    observaciones: "",
    juezId: null,
    createdAt: new Date("2025-04-13T15:22:00"),
    updatedAt: new Date("2025-04-13T15:22:00"),
    nombre: "Sergio Castillo Mora",
  },
];

// ─── Mejores piezas ────────────────────────────────────────────────────────────

export const MOCK_BEST_FISH: BestFish[] = [
  {
    id: "c-007",
    longitudCm: 34,
    puntos: 780,
    nombre: "Luis Álvarez Suárez",
    manga: 8,
    hora: "16:42",
    createdAt: new Date("2025-04-14T16:42:00"),
  },
  {
    id: "c-008",
    longitudCm: 32,
    puntos: 740,
    nombre: "Javier Fernández Lago",
    manga: 1,
    hora: "09:18",
    createdAt: new Date("2025-04-13T09:18:00"),
  },
  {
    id: "c-009",
    longitudCm: 31,
    puntos: 720,
    nombre: "Carlos Rodríguez Vega",
    manga: 2,
    hora: "08:45",
    createdAt: new Date("2025-04-13T08:45:00"),
  },
  {
    id: "c-010",
    longitudCm: 30,
    puntos: 700,
    nombre: "Pablo Martínez Torres",
    manga: 4,
    hora: "15:05",
    createdAt: new Date("2025-04-13T15:05:00"),
  },
  {
    id: "c-011",
    longitudCm: 29,
    puntos: 680,
    nombre: "Sergio Castillo Mora",
    manga: 3,
    hora: "15:22",
    createdAt: new Date("2025-04-13T15:22:00"),
  },
];

// ─── Stats por manga (las 8 mangas) ───────────────────────────────────────────

export const MOCK_MANGA_STATS: MangaStats[] = MANGAS.map((m) => {
  // Datos de ejemplo por manga — volumen decreciente porque el día 2 aún no ha terminado
  const base: Record<number, { capturas: number; validas: number; puntos: number; pescadores: number }> = {
    1: { capturas: 18, validas: 16, puntos: 10_120, pescadores: 12 },
    2: { capturas: 20, validas: 18, puntos: 11_360, pescadores: 12 },
    3: { capturas: 16, validas: 15, puntos: 9_480,  pescadores: 12 },
    4: { capturas: 18, validas: 16, puntos: 10_200, pescadores: 12 },
    5: { capturas: 14, validas: 12, puntos:  7_680,  pescadores: 12 },
    6: { capturas: 12, validas: 11, puntos:  6_920,  pescadores: 12 },
    7: { capturas: 10, validas:  9, puntos:  5_580,  pescadores: 12 },
    8: { capturas:  8, validas:  7, puntos:  4_360,  pescadores: 12 },
  };

  const d = base[m.numero] ?? { capturas: 0, validas: 0, puntos: 0, pescadores: 0 };

  return {
    manga: m.numero,
    dia: m.dia,
    sesion: m.sesion,
    turno: m.turno,
    totalCapturas: d.capturas,
    capturasValidas: d.validas,
    totalPuntos: d.puntos,
    pescadoresParticipantes: d.pescadores,
  };
});

// ─── Respuesta completa de stats (simula /api/stats) ──────────────────────────

export const MOCK_STATS_RESPONSE = {
  totalPescadores: MOCK_PARTICIPANTES.length,
  totalCapturas: MOCK_CLASIFICACION.reduce((acc, p) => acc + p.totalCapturas, 0),
  totalPuntos: MOCK_CLASIFICACION.reduce((acc, p) => acc + p.totalPuntos, 0),
  mangasActivas: MOCK_MANGA_STATS.filter((m) => m.totalCapturas > 0).length,
  topPescadores: MOCK_CLASIFICACION.slice(0, 5),
  mangaStats: MOCK_MANGA_STATS,
  recentCatches: MOCK_RECENT_CATCHES,
  bestFish: MOCK_BEST_FISH,
};
