/**
 * Mock data simulando respuestas de base de datos.
 * Clasificación individual de pescadores — VI Campeonato Nacional Salmónidos Lance Mosca
 */

import type {
  Participante,
  PescadorStats,
  RecentCatch,
  BestFish,
  MangaStats,
} from "@/types";

// ─── Participantes ─────────────────────────────────────────────────────────────

export const MOCK_PARTICIPANTES: Participante[] = [
  {
    id: "p-001",
    nombre: "Carlos Rodríguez Vega",
    plica: "01",
    club: "SD Pesca León",
    tramo: "Tramo 1 - Boñar",
    rio: "Río Porma",
    createdAt: new Date("2025-03-01"),
    updatedAt: new Date("2025-03-01"),
  },
  {
    id: "p-002",
    nombre: "Javier Fernández Lago",
    plica: "02",
    club: "Club Mosca Galicia",
    tramo: "Tramo 2 - Valdeón",
    rio: "Río Cares",
    createdAt: new Date("2025-03-01"),
    updatedAt: new Date("2025-03-01"),
  },
  {
    id: "p-003",
    nombre: "Marcos García Prieto",
    plica: "03",
    club: "AM Pesca Madrid",
    tramo: "Tramo 1 - Boñar",
    rio: "Río Porma",
    createdAt: new Date("2025-03-01"),
    updatedAt: new Date("2025-03-01"),
  },
  {
    id: "p-004",
    nombre: "Luis Álvarez Suárez",
    plica: "04",
    club: "Club Salmonídeos Asturias",
    tramo: "Tramo 3 - Riaño",
    rio: "Río Esla",
    createdAt: new Date("2025-03-01"),
    updatedAt: new Date("2025-03-01"),
  },
  {
    id: "p-005",
    nombre: "Pablo Martínez Torres",
    plica: "05",
    club: "SD Pesca León",
    tramo: "Tramo A - Ponferrada",
    rio: "Río Sil",
    createdAt: new Date("2025-03-01"),
    updatedAt: new Date("2025-03-01"),
  },
  {
    id: "p-006",
    nombre: "Antonio Iglesias Ramos",
    plica: "06",
    club: "Club Mosca Cantabria",
    tramo: "Tramo 2 - Valdeón",
    rio: "Río Cares",
    createdAt: new Date("2025-03-01"),
    updatedAt: new Date("2025-03-01"),
  },
  {
    id: "p-007",
    nombre: "David Blanco Herrero",
    plica: "07",
    club: "Federación Pesca Castilla y León",
    tramo: "Tramo B - Quiroga",
    rio: "Río Sil",
    createdAt: new Date("2025-03-02"),
    updatedAt: new Date("2025-03-02"),
  },
  {
    id: "p-008",
    nombre: "Sergio Castillo Mora",
    plica: "08",
    club: "Club Mosca Galicia",
    tramo: "Tramo 1 - Puebla de Sanabria",
    rio: "Río Tera",
    createdAt: new Date("2025-03-02"),
    updatedAt: new Date("2025-03-02"),
  },
  {
    id: "p-009",
    nombre: "Roberto Fuentes Díaz",
    plica: "09",
    club: "AM Pesca Madrid",
    tramo: "Tramo 3 - Riaño",
    rio: "Río Esla",
    createdAt: new Date("2025-03-02"),
    updatedAt: new Date("2025-03-02"),
  },
  {
    id: "p-010",
    nombre: "Fernando Ortega Nieto",
    plica: "10",
    club: "Club Salmonídeos Asturias",
    tramo: "Tramo 2 - Puebla de Sanabria",
    rio: "Río Tera",
    createdAt: new Date("2025-03-02"),
    updatedAt: new Date("2025-03-02"),
  },
  {
    id: "p-011",
    nombre: "Andrés López Sánchez",
    plica: "11",
    club: "SD Pesca León",
    tramo: "Tramo 1 - Boñar",
    rio: "Río Porma",
    createdAt: new Date("2025-03-03"),
    updatedAt: new Date("2025-03-03"),
  },
  {
    id: "p-012",
    nombre: "Miguel Pérez Castro",
    plica: "12",
    club: "Club Mosca Cantabria",
    tramo: "Tramo A - Ponferrada",
    rio: "Río Sil",
    createdAt: new Date("2025-03-03"),
    updatedAt: new Date("2025-03-03"),
  },
  {
    id: "p-013",
    nombre: "Raúl González Expósito",
    plica: "13",
    club: "Federación Pesca Castilla y León",
    tramo: "Tramo 2 - Valdeón",
    rio: "Río Cares",
    createdAt: new Date("2025-03-03"),
    updatedAt: new Date("2025-03-03"),
  },
  {
    id: "p-014",
    nombre: "Iván Moreno Bravo",
    plica: "14",
    club: "AM Pesca Madrid",
    tramo: "Tramo 3 - Riaño",
    rio: "Río Esla",
    createdAt: new Date("2025-03-03"),
    updatedAt: new Date("2025-03-03"),
  },
  {
    id: "p-015",
    nombre: "Óscar Jiménez Navarro",
    plica: "15",
    club: "Club Mosca Galicia",
    tramo: "Tramo B - Quiroga",
    rio: "Río Sil",
    createdAt: new Date("2025-03-04"),
    updatedAt: new Date("2025-03-04"),
  },
  {
    id: "p-016",
    nombre: "Tomás Serrano Gil",
    plica: "16",
    club: "SD Pesca León",
    tramo: "Tramo 1 - Puebla de Sanabria",
    rio: "Río Tera",
    createdAt: new Date("2025-03-04"),
    updatedAt: new Date("2025-03-04"),
  },
  {
    id: "p-017",
    nombre: "Eduardo Rubio Vargas",
    plica: "17",
    club: "Club Salmonídeos Asturias",
    tramo: "Tramo 1 - Boñar",
    rio: "Río Porma",
    createdAt: new Date("2025-03-04"),
    updatedAt: new Date("2025-03-04"),
  },
  {
    id: "p-018",
    nombre: "Vicente Molina Cano",
    plica: "18",
    club: "Club Mosca Cantabria",
    tramo: "Tramo 3 - Riaño",
    rio: "Río Esla",
    createdAt: new Date("2025-03-04"),
    updatedAt: new Date("2025-03-04"),
  },
  {
    id: "p-019",
    nombre: "Adrián Cruz Mendoza",
    plica: "19",
    club: "Federación Pesca Castilla y León",
    tramo: "Tramo A - Ponferrada",
    rio: "Río Sil",
    createdAt: new Date("2025-03-05"),
    updatedAt: new Date("2025-03-05"),
  },
  {
    id: "p-020",
    nombre: "Manuel Romero Peña",
    plica: "20",
    club: "AM Pesca Madrid",
    tramo: "Tramo 2 - Puebla de Sanabria",
    rio: "Río Tera",
    createdAt: new Date("2025-03-05"),
    updatedAt: new Date("2025-03-05"),
  },
  {
    id: "p-021",
    nombre: "Héctor Reyes Campos",
    plica: "21",
    club: "Club Mosca Galicia",
    tramo: "Tramo 2 - Valdeón",
    rio: "Río Cares",
    createdAt: new Date("2025-03-05"),
    updatedAt: new Date("2025-03-05"),
  },
  {
    id: "p-022",
    nombre: "Nicolás Delgado Vidal",
    plica: "22",
    club: "SD Pesca León",
    tramo: "Tramo 3 - Riaño",
    rio: "Río Esla",
    createdAt: new Date("2025-03-05"),
    updatedAt: new Date("2025-03-05"),
  },
  {
    id: "p-023",
    nombre: "Gonzalo Muñoz Tejeda",
    plica: "23",
    club: "Club Salmonídeos Asturias",
    tramo: "Tramo B - Quiroga",
    rio: "Río Sil",
    createdAt: new Date("2025-03-06"),
    updatedAt: new Date("2025-03-06"),
  },
  {
    id: "p-024",
    nombre: "Felipe Aguilar Soler",
    plica: "24",
    club: "Club Mosca Cantabria",
    tramo: "Tramo 1 - Puebla de Sanabria",
    rio: "Río Tera",
    createdAt: new Date("2025-03-06"),
    updatedAt: new Date("2025-03-06"),
  },
];

// ─── Clasificación individual ──────────────────────────────────────────────────

export const MOCK_CLASIFICACION: PescadorStats[] = [
  {
    pescadorId: "p-004",
    nombre: "Luis Álvarez Suárez",
    plica: "04",
    club: "Club Salmonídeos Asturias",
    tramo: "Tramo 3 - Riaño",
    rio: "Río Esla",
    totalCapturas: 9,
    capturasValidas: 8,
    capturasMenores18: 1,
    totalCm: 218,
    totalPuntos: 5_520,
    mejorPieza: 34,
    posicion: 1,
  },
  {
    pescadorId: "p-002",
    nombre: "Javier Fernández Lago",
    plica: "02",
    club: "Club Mosca Galicia",
    tramo: "Tramo 2 - Valdeón",
    rio: "Río Cares",
    totalCapturas: 8,
    capturasValidas: 8,
    capturasMenores18: 0,
    totalCm: 204,
    totalPuntos: 5_180,
    mejorPieza: 32,
    posicion: 2,
  },
  {
    pescadorId: "p-001",
    nombre: "Carlos Rodríguez Vega",
    plica: "01",
    club: "SD Pesca León",
    tramo: "Tramo 1 - Boñar",
    rio: "Río Porma",
    totalCapturas: 8,
    capturasValidas: 7,
    capturasMenores18: 1,
    totalCm: 192,
    totalPuntos: 4_940,
    mejorPieza: 31,
    posicion: 3,
  },
  {
    pescadorId: "p-005",
    nombre: "Pablo Martínez Torres",
    plica: "05",
    club: "SD Pesca León",
    tramo: "Tramo A - Ponferrada",
    rio: "Río Sil",
    totalCapturas: 7,
    capturasValidas: 7,
    capturasMenores18: 0,
    totalCm: 181,
    totalPuntos: 4_720,
    mejorPieza: 30,
    posicion: 4,
  },
  {
    pescadorId: "p-008",
    nombre: "Sergio Castillo Mora",
    plica: "08",
    club: "Club Mosca Galicia",
    tramo: "Tramo 1 - Puebla de Sanabria",
    rio: "Río Tera",
    totalCapturas: 7,
    capturasValidas: 6,
    capturasMenores18: 1,
    totalCm: 168,
    totalPuntos: 4_460,
    mejorPieza: 29,
    posicion: 5,
  },
  {
    pescadorId: "p-009",
    nombre: "Roberto Fuentes Díaz",
    plica: "09",
    club: "AM Pesca Madrid",
    tramo: "Tramo 3 - Riaño",
    rio: "Río Esla",
    totalCapturas: 6,
    capturasValidas: 6,
    capturasMenores18: 0,
    totalCm: 158,
    totalPuntos: 4_260,
    mejorPieza: 28,
    posicion: 6,
  },
  {
    pescadorId: "p-015",
    nombre: "Óscar Jiménez Navarro",
    plica: "15",
    club: "Club Mosca Galicia",
    tramo: "Tramo B - Quiroga",
    rio: "Río Sil",
    totalCapturas: 6,
    capturasValidas: 5,
    capturasMenores18: 1,
    totalCm: 145,
    totalPuntos: 3_980,
    mejorPieza: 27,
    posicion: 7,
  },
  {
    pescadorId: "p-003",
    nombre: "Marcos García Prieto",
    plica: "03",
    club: "AM Pesca Madrid",
    tramo: "Tramo 1 - Boñar",
    rio: "Río Porma",
    totalCapturas: 6,
    capturasValidas: 5,
    capturasMenores18: 1,
    totalCm: 138,
    totalPuntos: 3_780,
    mejorPieza: 26,
    posicion: 8,
  },
  {
    pescadorId: "p-013",
    nombre: "Raúl González Expósito",
    plica: "13",
    club: "Federación Pesca Castilla y León",
    tramo: "Tramo 2 - Valdeón",
    rio: "Río Cares",
    totalCapturas: 5,
    capturasValidas: 5,
    capturasMenores18: 0,
    totalCm: 128,
    totalPuntos: 3_560,
    mejorPieza: 26,
    posicion: 9,
  },
  {
    pescadorId: "p-006",
    nombre: "Antonio Iglesias Ramos",
    plica: "06",
    club: "Club Mosca Cantabria",
    tramo: "Tramo 2 - Valdeón",
    rio: "Río Cares",
    totalCapturas: 5,
    capturasValidas: 5,
    capturasMenores18: 0,
    totalCm: 122,
    totalPuntos: 3_440,
    mejorPieza: 25,
    posicion: 10,
  },
  {
    pescadorId: "p-007",
    nombre: "David Blanco Herrero",
    plica: "07",
    club: "Federación Pesca Castilla y León",
    tramo: "Tramo B - Quiroga",
    rio: "Río Sil",
    totalCapturas: 5,
    capturasValidas: 4,
    capturasMenores18: 1,
    totalCm: 108,
    totalPuntos: 3_100,
    mejorPieza: 24,
    posicion: 11,
  },
  {
    pescadorId: "p-011",
    nombre: "Andrés López Sánchez",
    plica: "11",
    club: "SD Pesca León",
    tramo: "Tramo 1 - Boñar",
    rio: "Río Porma",
    totalCapturas: 4,
    capturasValidas: 4,
    capturasMenores18: 0,
    totalCm: 98,
    totalPuntos: 2_960,
    mejorPieza: 27,
    posicion: 12,
  },
  {
    pescadorId: "p-014",
    nombre: "Iván Moreno Bravo",
    plica: "14",
    club: "AM Pesca Madrid",
    tramo: "Tramo 3 - Riaño",
    rio: "Río Esla",
    totalCapturas: 4,
    capturasValidas: 4,
    capturasMenores18: 0,
    totalCm: 94,
    totalPuntos: 2_880,
    mejorPieza: 25,
    posicion: 13,
  },
  {
    pescadorId: "p-019",
    nombre: "Adrián Cruz Mendoza",
    plica: "19",
    club: "Federación Pesca Castilla y León",
    tramo: "Tramo A - Ponferrada",
    rio: "Río Sil",
    totalCapturas: 4,
    capturasValidas: 3,
    capturasMenores18: 1,
    totalCm: 82,
    totalPuntos: 2_540,
    mejorPieza: 28,
    posicion: 14,
  },
  {
    pescadorId: "p-012",
    nombre: "Miguel Pérez Castro",
    plica: "12",
    club: "Club Mosca Cantabria",
    tramo: "Tramo A - Ponferrada",
    rio: "Río Sil",
    totalCapturas: 3,
    capturasValidas: 3,
    capturasMenores18: 0,
    totalCm: 76,
    totalPuntos: 2_380,
    mejorPieza: 26,
    posicion: 15,
  },
  {
    pescadorId: "p-017",
    nombre: "Eduardo Rubio Vargas",
    plica: "17",
    club: "Club Salmonídeos Asturias",
    tramo: "Tramo 1 - Boñar",
    rio: "Río Porma",
    totalCapturas: 3,
    capturasValidas: 3,
    capturasMenores18: 0,
    totalCm: 71,
    totalPuntos: 2_220,
    mejorPieza: 24,
    posicion: 16,
  },
  {
    pescadorId: "p-022",
    nombre: "Nicolás Delgado Vidal",
    plica: "22",
    club: "SD Pesca León",
    tramo: "Tramo 3 - Riaño",
    rio: "Río Esla",
    totalCapturas: 3,
    capturasValidas: 2,
    capturasMenores18: 1,
    totalCm: 58,
    totalPuntos: 1_820,
    mejorPieza: 31,
    posicion: 17,
  },
  {
    pescadorId: "p-010",
    nombre: "Fernando Ortega Nieto",
    plica: "10",
    club: "Club Salmonídeos Asturias",
    tramo: "Tramo 2 - Puebla de Sanabria",
    rio: "Río Tera",
    totalCapturas: 2,
    capturasValidas: 2,
    capturasMenores18: 0,
    totalCm: 49,
    totalPuntos: 1_580,
    mejorPieza: 25,
    posicion: 18,
  },
  {
    pescadorId: "p-021",
    nombre: "Héctor Reyes Campos",
    plica: "21",
    club: "Club Mosca Galicia",
    tramo: "Tramo 2 - Valdeón",
    rio: "Río Cares",
    totalCapturas: 2,
    capturasValidas: 2,
    capturasMenores18: 0,
    totalCm: 44,
    totalPuntos: 1_480,
    mejorPieza: 23,
    posicion: 19,
  },
  {
    pescadorId: "p-016",
    nombre: "Tomás Serrano Gil",
    plica: "16",
    club: "SD Pesca León",
    tramo: "Tramo 1 - Puebla de Sanabria",
    rio: "Río Tera",
    totalCapturas: 2,
    capturasValidas: 1,
    capturasMenores18: 1,
    totalCm: 32,
    totalPuntos: 740,
    mejorPieza: 32,
    posicion: 20,
  },
  {
    pescadorId: "p-018",
    nombre: "Vicente Molina Cano",
    plica: "18",
    club: "Club Mosca Cantabria",
    tramo: "Tramo 3 - Riaño",
    rio: "Río Esla",
    totalCapturas: 1,
    capturasValidas: 1,
    capturasMenores18: 0,
    totalCm: 21,
    totalPuntos: 520,
    mejorPieza: 21,
    posicion: 21,
  },
  {
    pescadorId: "p-020",
    nombre: "Manuel Romero Peña",
    plica: "20",
    club: "AM Pesca Madrid",
    tramo: "Tramo 2 - Puebla de Sanabria",
    rio: "Río Tera",
    totalCapturas: 1,
    capturasValidas: 1,
    capturasMenores18: 0,
    totalCm: 19,
    totalPuntos: 480,
    mejorPieza: 19,
    posicion: 22,
  },
  {
    pescadorId: "p-023",
    nombre: "Gonzalo Muñoz Tejeda",
    plica: "23",
    club: "Club Salmonídeos Asturias",
    tramo: "Tramo B - Quiroga",
    rio: "Río Sil",
    totalCapturas: 1,
    capturasValidas: 0,
    capturasMenores18: 1,
    totalCm: 15,
    totalPuntos: 15,
    mejorPieza: 15,
    posicion: 23,
  },
  {
    pescadorId: "p-024",
    nombre: "Felipe Aguilar Soler",
    plica: "24",
    club: "Club Mosca Cantabria",
    tramo: "Tramo 1 - Puebla de Sanabria",
    rio: "Río Tera",
    totalCapturas: 0,
    capturasValidas: 0,
    capturasMenores18: 0,
    totalCm: 0,
    totalPuntos: 0,
    mejorPieza: 0,
    posicion: 24,
  },
];

// ─── Últimas capturas ──────────────────────────────────────────────────────────

export const MOCK_RECENT_CATCHES: RecentCatch[] = [
  {
    id: "c-001",
    pescadorId: "p-004",
    sessionId: "s-004",
    manga: 3,
    tramo: "Tramo 3 - Riaño",
    rio: "Río Esla",
    longitudCm: 34,
    puntos: 780,
    valida: true,
    hora: "11:42",
    observaciones: "",
    juezId: null,
    createdAt: new Date("2025-04-13T11:42:00"),
    updatedAt: new Date("2025-04-13T11:42:00"),
    nombre: "Luis Álvarez Suárez",
  },
  {
    id: "c-002",
    pescadorId: "p-002",
    sessionId: "s-002",
    manga: 3,
    tramo: "Tramo 2 - Valdeón",
    rio: "Río Cares",
    longitudCm: 32,
    puntos: 740,
    valida: true,
    hora: "11:28",
    observaciones: "",
    juezId: null,
    createdAt: new Date("2025-04-13T11:28:00"),
    updatedAt: new Date("2025-04-13T11:28:00"),
    nombre: "Javier Fernández Lago",
  },
  {
    id: "c-003",
    pescadorId: "p-001",
    sessionId: "s-001",
    manga: 3,
    tramo: "Tramo 1 - Boñar",
    rio: "Río Porma",
    longitudCm: 28,
    puntos: 660,
    valida: true,
    hora: "11:15",
    observaciones: "",
    juezId: null,
    createdAt: new Date("2025-04-13T11:15:00"),
    updatedAt: new Date("2025-04-13T11:15:00"),
    nombre: "Carlos Rodríguez Vega",
  },
  {
    id: "c-004",
    pescadorId: "p-005",
    sessionId: "s-005",
    manga: 2,
    tramo: "Tramo A - Ponferrada",
    rio: "Río Sil",
    longitudCm: 26,
    puntos: 620,
    valida: true,
    hora: "10:54",
    observaciones: "",
    juezId: null,
    createdAt: new Date("2025-04-13T10:54:00"),
    updatedAt: new Date("2025-04-13T10:54:00"),
    nombre: "Pablo Martínez Torres",
  },
  {
    id: "c-005",
    pescadorId: "p-009",
    sessionId: "s-009",
    manga: 2,
    tramo: "Tramo 3 - Riaño",
    rio: "Río Esla",
    longitudCm: 16,
    puntos: 15,
    valida: false,
    hora: "10:40",
    observaciones: "Medida inferior al mínimo",
    juezId: null,
    createdAt: new Date("2025-04-13T10:40:00"),
    updatedAt: new Date("2025-04-13T10:40:00"),
    nombre: "Roberto Fuentes Díaz",
  },
  {
    id: "c-006",
    pescadorId: "p-008",
    sessionId: "s-008",
    manga: 2,
    tramo: "Tramo 1 - Puebla de Sanabria",
    rio: "Río Tera",
    longitudCm: 29,
    puntos: 680,
    valida: true,
    hora: "10:22",
    observaciones: "",
    juezId: null,
    createdAt: new Date("2025-04-13T10:22:00"),
    updatedAt: new Date("2025-04-13T10:22:00"),
    nombre: "Sergio Castillo Mora",
  },
];

// ─── Mejores piezas ────────────────────────────────────────────────────────────

export const MOCK_BEST_FISH: BestFish[] = [
  {
    id: "c-007",
    longitudCm: 34,
    puntos: 780,
    nombre: "Luis Álvarez Suárez",
    manga: 3,
    hora: "11:42",
    createdAt: new Date("2025-04-13T11:42:00"),
  },
  {
    id: "c-008",
    longitudCm: 32,
    puntos: 740,
    nombre: "Javier Fernández Lago",
    manga: 2,
    hora: "09:18",
    createdAt: new Date("2025-04-13T09:18:00"),
  },
  {
    id: "c-009",
    longitudCm: 31,
    puntos: 720,
    nombre: "Carlos Rodríguez Vega",
    manga: 1,
    hora: "08:45",
    createdAt: new Date("2025-04-13T08:45:00"),
  },
  {
    id: "c-010",
    longitudCm: 30,
    puntos: 700,
    nombre: "Pablo Martínez Torres",
    manga: 3,
    hora: "11:05",
    createdAt: new Date("2025-04-13T11:05:00"),
  },
  {
    id: "c-011",
    longitudCm: 29,
    puntos: 680,
    nombre: "Sergio Castillo Mora",
    manga: 2,
    hora: "10:22",
    createdAt: new Date("2025-04-13T10:22:00"),
  },
];

// ─── Stats por manga ──────────────────────────────────────────────────────────

export const MOCK_MANGA_STATS: MangaStats[] = [
  {
    manga: 1,
    totalCapturas: 38,
    capturasValidas: 34,
    totalPuntos: 21_480,
    pescadoresParticipantes: 24,
  },
  {
    manga: 2,
    totalCapturas: 32,
    capturasValidas: 28,
    totalPuntos: 18_240,
    pescadoresParticipantes: 24,
  },
  {
    manga: 3,
    totalCapturas: 18,
    capturasValidas: 16,
    totalPuntos: 10_560,
    pescadoresParticipantes: 21,
  },
];

// ─── Respuesta completa de stats (simula /api/stats) ──────────────────────────

export const MOCK_STATS_RESPONSE = {
  totalPescadores: MOCK_PARTICIPANTES.length,
  totalCapturas: MOCK_CLASIFICACION.reduce((acc, p) => acc + p.totalCapturas, 0),
  totalPuntos: MOCK_CLASIFICACION.reduce((acc, p) => acc + p.totalPuntos, 0),
  mangasActivas: MOCK_MANGA_STATS.length,
  topPescadores: MOCK_CLASIFICACION.slice(0, 5),
  mangaStats: MOCK_MANGA_STATS,
  recentCatches: MOCK_RECENT_CATCHES,
  bestFish: MOCK_BEST_FISH,
};
