-- =============================================================================
-- 0002 — Seed comunidades autónomas + provincias (INE codes, idempotent).
-- =============================================================================

-- ─── Comunidades Autónomas ───────────────────────────────────────────────────
INSERT INTO comunidades_autonomas (codigo, nombre, slug) VALUES
  ('01', 'Andalucía',                         'andalucia'),
  ('02', 'Aragón',                            'aragon'),
  ('03', 'Asturias, Principado de',           'asturias'),
  ('04', 'Balears, Illes',                    'illes-balears'),
  ('05', 'Canarias',                          'canarias'),
  ('06', 'Cantabria',                         'cantabria'),
  ('07', 'Castilla y León',                   'castilla-y-leon'),
  ('08', 'Castilla-La Mancha',                'castilla-la-mancha'),
  ('09', 'Cataluña',                          'cataluna'),
  ('10', 'Comunitat Valenciana',              'comunitat-valenciana'),
  ('11', 'Extremadura',                       'extremadura'),
  ('12', 'Galicia',                           'galicia'),
  ('13', 'Madrid, Comunidad de',              'madrid'),
  ('14', 'Murcia, Región de',                 'murcia'),
  ('15', 'Navarra, Comunidad Foral de',       'navarra'),
  ('16', 'País Vasco',                        'pais-vasco'),
  ('17', 'Rioja, La',                         'la-rioja'),
  ('18', 'Ceuta',                             'ceuta'),
  ('19', 'Melilla',                           'melilla')
ON CONFLICT (codigo) DO NOTHING;

-- ─── Provincias ──────────────────────────────────────────────────────────────
-- Resolve comunidad_autonoma_id from INE ccaa codigo at insert time.
INSERT INTO provincias (codigo, nombre, slug, comunidad_autonoma_id) VALUES
  ('01', 'Araba/Álava',             'araba-alava',             (SELECT id FROM comunidades_autonomas WHERE codigo = '16')),
  ('02', 'Albacete',                'albacete',                (SELECT id FROM comunidades_autonomas WHERE codigo = '08')),
  ('03', 'Alicante/Alacant',        'alicante-alacant',        (SELECT id FROM comunidades_autonomas WHERE codigo = '10')),
  ('04', 'Almería',                 'almeria',                 (SELECT id FROM comunidades_autonomas WHERE codigo = '01')),
  ('05', 'Ávila',                   'avila',                   (SELECT id FROM comunidades_autonomas WHERE codigo = '07')),
  ('06', 'Badajoz',                 'badajoz',                 (SELECT id FROM comunidades_autonomas WHERE codigo = '11')),
  ('07', 'Balears, Illes',          'illes-balears-provincia', (SELECT id FROM comunidades_autonomas WHERE codigo = '04')),
  ('08', 'Barcelona',               'barcelona',               (SELECT id FROM comunidades_autonomas WHERE codigo = '09')),
  ('09', 'Burgos',                  'burgos',                  (SELECT id FROM comunidades_autonomas WHERE codigo = '07')),
  ('10', 'Cáceres',                 'caceres',                 (SELECT id FROM comunidades_autonomas WHERE codigo = '11')),
  ('11', 'Cádiz',                   'cadiz',                   (SELECT id FROM comunidades_autonomas WHERE codigo = '01')),
  ('12', 'Castellón/Castelló',      'castellon-castello',      (SELECT id FROM comunidades_autonomas WHERE codigo = '10')),
  ('13', 'Ciudad Real',             'ciudad-real',             (SELECT id FROM comunidades_autonomas WHERE codigo = '08')),
  ('14', 'Córdoba',                 'cordoba',                 (SELECT id FROM comunidades_autonomas WHERE codigo = '01')),
  ('15', 'Coruña, A',               'a-coruna',                (SELECT id FROM comunidades_autonomas WHERE codigo = '12')),
  ('16', 'Cuenca',                  'cuenca',                  (SELECT id FROM comunidades_autonomas WHERE codigo = '08')),
  ('17', 'Girona',                  'girona',                  (SELECT id FROM comunidades_autonomas WHERE codigo = '09')),
  ('18', 'Granada',                 'granada',                 (SELECT id FROM comunidades_autonomas WHERE codigo = '01')),
  ('19', 'Guadalajara',             'guadalajara',             (SELECT id FROM comunidades_autonomas WHERE codigo = '08')),
  ('20', 'Gipuzkoa',                'gipuzkoa',                (SELECT id FROM comunidades_autonomas WHERE codigo = '16')),
  ('21', 'Huelva',                  'huelva',                  (SELECT id FROM comunidades_autonomas WHERE codigo = '01')),
  ('22', 'Huesca',                  'huesca',                  (SELECT id FROM comunidades_autonomas WHERE codigo = '02')),
  ('23', 'Jaén',                    'jaen',                    (SELECT id FROM comunidades_autonomas WHERE codigo = '01')),
  ('24', 'León',                    'leon',                    (SELECT id FROM comunidades_autonomas WHERE codigo = '07')),
  ('25', 'Lleida',                  'lleida',                  (SELECT id FROM comunidades_autonomas WHERE codigo = '09')),
  ('26', 'Rioja, La',               'la-rioja-provincia',      (SELECT id FROM comunidades_autonomas WHERE codigo = '17')),
  ('27', 'Lugo',                    'lugo',                    (SELECT id FROM comunidades_autonomas WHERE codigo = '12')),
  ('28', 'Madrid',                  'madrid-provincia',        (SELECT id FROM comunidades_autonomas WHERE codigo = '13')),
  ('29', 'Málaga',                  'malaga',                  (SELECT id FROM comunidades_autonomas WHERE codigo = '01')),
  ('30', 'Murcia',                  'murcia-provincia',        (SELECT id FROM comunidades_autonomas WHERE codigo = '14')),
  ('31', 'Navarra',                 'navarra-provincia',       (SELECT id FROM comunidades_autonomas WHERE codigo = '15')),
  ('32', 'Ourense',                 'ourense',                 (SELECT id FROM comunidades_autonomas WHERE codigo = '12')),
  ('33', 'Asturias',                'asturias-provincia',      (SELECT id FROM comunidades_autonomas WHERE codigo = '03')),
  ('34', 'Palencia',                'palencia',                (SELECT id FROM comunidades_autonomas WHERE codigo = '07')),
  ('35', 'Palmas, Las',             'las-palmas',              (SELECT id FROM comunidades_autonomas WHERE codigo = '05')),
  ('36', 'Pontevedra',              'pontevedra',              (SELECT id FROM comunidades_autonomas WHERE codigo = '12')),
  ('37', 'Salamanca',               'salamanca',               (SELECT id FROM comunidades_autonomas WHERE codigo = '07')),
  ('38', 'Santa Cruz de Tenerife',  'santa-cruz-de-tenerife',  (SELECT id FROM comunidades_autonomas WHERE codigo = '05')),
  ('39', 'Cantabria',               'cantabria-provincia',     (SELECT id FROM comunidades_autonomas WHERE codigo = '06')),
  ('40', 'Segovia',                 'segovia',                 (SELECT id FROM comunidades_autonomas WHERE codigo = '07')),
  ('41', 'Sevilla',                 'sevilla',                 (SELECT id FROM comunidades_autonomas WHERE codigo = '01')),
  ('42', 'Soria',                   'soria',                   (SELECT id FROM comunidades_autonomas WHERE codigo = '07')),
  ('43', 'Tarragona',               'tarragona',               (SELECT id FROM comunidades_autonomas WHERE codigo = '09')),
  ('44', 'Teruel',                  'teruel',                  (SELECT id FROM comunidades_autonomas WHERE codigo = '02')),
  ('45', 'Toledo',                  'toledo',                  (SELECT id FROM comunidades_autonomas WHERE codigo = '08')),
  ('46', 'Valencia/València',       'valencia-valencia',       (SELECT id FROM comunidades_autonomas WHERE codigo = '10')),
  ('47', 'Valladolid',              'valladolid',              (SELECT id FROM comunidades_autonomas WHERE codigo = '07')),
  ('48', 'Bizkaia',                 'bizkaia',                 (SELECT id FROM comunidades_autonomas WHERE codigo = '16')),
  ('49', 'Zamora',                  'zamora',                  (SELECT id FROM comunidades_autonomas WHERE codigo = '07')),
  ('50', 'Zaragoza',                'zaragoza',                (SELECT id FROM comunidades_autonomas WHERE codigo = '02')),
  ('51', 'Ceuta',                   'ceuta-provincia',         (SELECT id FROM comunidades_autonomas WHERE codigo = '18')),
  ('52', 'Melilla',                 'melilla-provincia',       (SELECT id FROM comunidades_autonomas WHERE codigo = '19'))
ON CONFLICT (codigo) DO NOTHING;
